DO NOT MERGE adding dev journey blog post
IBM/acme-freight-recommendation pull request #1
Opened 2017-05-31 16:48 UTC by joesepi

2017-05-31 17:57 UTC, ashumz commented on dev-journey-blog.md
> +If you look at the actions in the repo, you'll see the functional code is broken into logical separations of concern. Then, the recommendations interface is made available to our application via APIs
link to part of repo with actions

2017-05-31 17:58 UTC, ashumz commented on dev-journey-blog.md
> +Acme Freight uses a serverless approach to respond to weather events. An action is triggered by a storm event; retailers affected by the weather event are identified; their stock and shipments are re
add link to repo where this code comes from (recommend.js)

2017-05-31 18:00 UTC, ashumz requested changes

2017-05-31 18:00 UTC, ashumz commented on dev-journey-blog.md
> +If you look at the actions in the repo, you'll see the functional code is broken into logical separations of concern. Then, the recommendations interface is made available to our application via APIs
add call to action to learn more about deploying an openwhisk app in bluemix - make sure we are pitching the API side of this as much as the serverless side 

should we think about adding a section about securing the openwhisk api's to tie in the bluemix native side? @svennam92 @joesepi

2017-05-31 22:13 UTC, joesepi commented on dev-journey-blog.md
> +If you look at the actions in the repo, you'll see the functional code is broken into logical separations of concern. Then, the recommendations interface is made available to our application via APIs
I'll try something here.

2017-05-31 23:54 UTC, ashumz approved these changes

2017-06-02 18:18 UTC, joesepi commented
Content approved. Work will continue in content platform. Closing this review.

2017-06-02 18:18 UTC, closed without merging